name: Deploy Open Tasks Wiki to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git info

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Quartz
        run: |
          git clone https://github.com/jackyzha0/quartz.git quartz-build
          cd quartz-build
          npm ci

      - name: Copy wiki content to Quartz
        run: |
          # Remove default content
          rm -rf quartz-build/content/*
          # Copy our wiki content
          cp -r open-tasks-wiki/* quartz-build/content/

      - name: Configure Quartz
        run: |
          cd quartz-build
          # Update base URL in quartz.config.ts
          # Adjust the repository name as needed
          sed -i 's|baseUrl: ".*"|baseUrl: "${{ github.repository_owner }}.github.io/open-tasks"|g' quartz.config.ts || true

      - name: Build Quartz site
        run: |
          cd quartz-build
          npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz-build/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
